---
title: "Annotated data sets contained in the `acnr` package"
author: "M. Pierre-Jean, P. Neuvial"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Annotated data sets contained in the `acnr` package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include=FALSE}
library("knitr")
opts_chunk$set(
dev='png', fig.width=5, fig.height=5
)
```

This vignette describes the annotated data sets contained in the `acnr` package.

```{r, include=FALSE}
library("acnr")
```

## Description of the annotated data sets

```{r}
tf <- .5
dataSets <- c("GSE29172", "GSE11976")

regList <- lapply(dataSets, FUN=function(ds) {
    regDat <- loadCnRegionData(dataSet=ds, tumorFraction=tf) 
    regs <- regDat[["region"]]
})
names(regList) <- dataSets

allregs <- unique(unlist(regList))
tab <- sapply(allregs, FUN=function(reg) {
    sapply(regList, FUN=function(rr) sum(rr==reg))
})
cap <- paste("Size of annotated copy-number regions for each of the", 
            length(dataSets), "data sets.")
if (require(xtable)) {
    print(xtable(tab, caption=cap, label="tab:regData",
                table.placement="!h", caption.placement="bottom"))
}
```

## Session information

```{r}
sessionInfo()
```

